src/main/java/com/coffice/app/posts/QuillFileVO.java, src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/board/BoardDAO.java, src/main/java/com/coffice/app/posts/board/BoardSerivce.java, src/main/java/com/coffice/app/posts/board/BoardVO.java, src/main/java/com/coffice/app/posts/notice/NoticeService.java, src/main/resources/database/mappers/BoardMapper.xml, src/main/resources/database/mappers/NoticeMapper.xml, src/main/resources/static/js/coffice/noticeUpdate.js, src/main/webapp/WEB-INF/views/board/add.jsp, src/main/webapp/WEB-INF/views/board/detail.jsp, src/main/webapp/WEB-INF/views/board/list.jsp, src/main/webapp/WEB-INF/views/board/update.jsp, src/main/webapp/WEB-INF/views/commons/result.jsp, src/main/webapp/WEB-INF/views/templates/sidebar.jsp, src/test/java/com/coffice/app/posts/board/BoardDAOTest.java
익명게시판 리스트 / 상세조회 / 추가 / 삭제 / 수정
- close #23 
<br>
---
추후 조회수 기능 만들 예정
=> Feat/#23 익명게시판 crud

src/main/webapp/WEB-INF/views/templates/ocModal.jsp
=> [fix/#31] 조직도 모달 버전 수정

pom.xml, src/main/java/com/coffice/app/chat/ChatController.java, src/main/java/com/coffice/app/chat/config/WebSocketConfig.java, src/main/java/com/coffice/app/chat/config/WebSocketStompBrokerConfig.java, src/main/java/com/coffice/app/chat/config/handler/ChatWebSocketHandler.java
stomp 연결
- close #43 
<br>
---
=> feat: #43 stomp 연결

src/main/java/com/coffice/app/documents/DocumentController.java, src/main/java/com/coffice/app/documents/DocumentVO.java, src/main/java/com/coffice/app/documents/forms/FormVO.java, src/main/java/com/coffice/app/documents/lines/ApprovalLineVO.java, src/main/java/com/coffice/app/documents/lines/ReferenceLineVO.java
=> [Refactor/#46] 문서 결재선 참조선 문서양식 vo 수정

pom.xml, src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/EventVO.java, src/main/java/com/coffice/app/events/holidays/HolidayDAO.java, src/main/java/com/coffice/app/events/holidays/HolidayService.java, src/main/java/com/coffice/app/events/holidays/HolidayVO.java, src/main/java/com/coffice/app/home/HomeController.java, src/main/resources/database/mappers/HolidayMapper.xml, src/main/resources/static/js/calendar/homeCalendar.js, src/test/java/com/coffice/app/events/holidays/HolidayServiceTest.java
공휴일 VO, table 생성
서버 내에서 공휴일 api 조회 후 테이블 insert
캘린더 랜더 시에 db에서 조회
- close #42
<br>
---
=> [refactor: #42] 공휴일api 수정

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/EventVO.java, src/main/java/com/coffice/app/events/schedule/ScheduleDAO.java, src/main/java/com/coffice/app/events/schedule/ScheduleService.java, src/main/resources/database/mappers/HolidayMapper.xml, src/main/resources/database/mappers/ScheduleMapper.xml, src/main/resources/static/js/calendar/homeCalendar.js, src/main/resources/static/js/calendar/scheduleCalendar.js, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/webapp/WEB-INF/views/events/schedule.jsp, src/main/webapp/WEB-INF/views/templates/ocModal.jsp
기본 일정조회 기능
전체 조회 : 캘린더 랜더 시 전체 공휴일, 일정 조회
단일 조회 : 일정 클릭 시 일정 정보 조회
- close #54
<br>
---
=> Feat/#54 일정관리 일정공휴일조회

src/main/java/com/coffice/app/home/HomeController.java, src/main/java/com/coffice/app/posts/notice/NoticeDAO.java, src/main/java/com/coffice/app/posts/notice/NoticeService.java, src/main/resources/database/mappers/NoticeMapper.xml, src/main/webapp/WEB-INF/views/index.jsp
메인 페이지에 공지사항 부분에 공지사항 불러와서 추가
- close #76 
<br>
---
=> Feat/#76 메인 페이지 공지사항 추가

src/main/java/com/coffice/app/users/UserController.java, src/main/java/com/coffice/app/users/UserDAO.java, src/main/java/com/coffice/app/users/UserService.java, src/main/resources/database/mappers/UserMapper.xml, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/templates/ocModal.jsp
조직도 모달 완성
- close #78 
<br>
---
유저 패키지 내에 조직도에 필요한 맵퍼, 메서드 추가 하였음
ocModal.jsp에서 버튼만 연결시키면 모달 불러올 수 있음.
=> feat/#78 조직도 ajax처리 (User 데이터처리)

src/main/java/com/coffice/app/chat/ChatController.java, src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/notice/NoticeController.java, src/main/resources/static/css/sidebar.css, src/main/resources/static/js/sidebar.js, src/main/webapp/WEB-INF/views/board/detail.jsp, src/main/webapp/WEB-INF/views/notice/detail.jsp, src/main/webapp/WEB-INF/views/templates/footModal.jsp, src/main/webapp/WEB-INF/views/templates/header.jsp, src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Reverts yangtori0407/coffice#84
=> Revert "Feat/#82 공지사항익명게시판메세지 사이드 바 수정"

src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/notice/NoticeController.java, src/main/resources/database/mappers/BoardMapper.xml, src/main/resources/static/js/posts/boardDetail.js, src/main/webapp/WEB-INF/views/board/add.jsp, src/main/webapp/WEB-INF/views/board/detail.jsp, src/main/webapp/WEB-INF/views/notice/detail.jsp, src/test/java/com/coffice/app/posts/board/BoardDAOTest.java, src/test/java/com/coffice/app/posts/notice/NoticeDAOTest.java
게시판과 댓글에 security로 userid를 받아서 작성자에 추가하는 로직
- close #36 
<br>
---
=> Refator/#36 게시판 댓글 작성자 추가 및 mapper 수정

src/main/resources/static/js/chat/add.js, src/main/webapp/WEB-INF/views/chat/addChat.jsp, src/main/webapp/WEB-INF/views/templates/ocModal.jsp, src/main/webapp/WEB-INF/views/templates/sample.jsp
모달 조직도로 채팅방에 사람 추가하기 및 중복, 본인 초대 막기
- close #93 
<br>
---
조직도 쓰시는 경우 변수가 겹치지 않게 조심해주세요!
만약 null로 인해 오류가 났을 경우 말해주세요~
=> Feat/#93 모달로 채팅방 사람 추가하기

pom.xml, src/main/java/com/coffice/app/users/UserController.java
dev 오류 수정 pom.xml userController
- close #105 
<br>
---
=> fix:#105 dev 오류 수정

src/main/java/com/coffice/app/chat/ChatController.java, src/main/java/com/coffice/app/chat/ChatDAO.java, src/main/java/com/coffice/app/chat/ChatService.java, src/main/java/com/coffice/app/chat/vo/ChatContentsVO.java, src/main/java/com/coffice/app/chat/vo/ChatPersonVO.java, src/main/java/com/coffice/app/chat/vo/ChatRoomVO.java, src/main/java/com/coffice/app/home/HomeController.java, src/main/resources/database/mappers/ChatMapper.xml, src/main/resources/static/css/chatAlert.css, src/main/resources/static/js/chat/chatStomp.js, src/main/resources/static/js/notification/notification.js, src/main/webapp/WEB-INF/views/chat/chatRoom.jsp, src/main/webapp/WEB-INF/views/chat/main.jsp, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/templates/footModal.jsp, src/main/webapp/WEB-INF/views/templates/header.jsp, src/main/webapp/WEB-INF/views/templates/top.jsp
채팅방 알림 기능
채팅 시 toast 기능으로 하단에 알림을 뜨게 함 
알림 끄기 켜기
- close #95 
<br>
---
=> Feat/#95 채팅방 알림 기능

src/main/java/com/coffice/app/chat/ChatController.java, src/main/java/com/coffice/app/home/HomeController.java, src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/notice/NoticeController.java, src/main/webapp/WEB-INF/views/board/detail.jsp, src/main/webapp/WEB-INF/views/board/list.jsp, src/main/webapp/WEB-INF/views/notice/detail.jsp, src/main/webapp/WEB-INF/views/notice/list.jsp, src/main/webapp/WEB-INF/views/templates/top.jsp
top 부분에 각 페이지 별로 해당 페이지의 이름을 넣을 수 있게 했습니다~
- close #{이슈넘버}
<br>
---
kind 라는 이름으로 넣었습니다~
게시판 > 익명게시판 > 작성하기
게시판 > 공지사항
이런 느낌으로 작성하였습니다
=> Fix:#114 게시판/메신저 헤더 제목 수정

src/main/java/com/coffice/app/security/LoginSuccessHandler.java, src/main/resources/static/js/chat/chatStomp.js, src/main/resources/static/js/notification/notification.js, src/main/webapp/WEB-INF/views/chat/addChat.jsp, src/main/webapp/WEB-INF/views/chat/chatRoom.jsp, src/main/webapp/WEB-INF/views/templates/ocModal.jsp, src/main/webapp/WEB-INF/views/templates/top.jsp
기존에 el 태그로 유저 id를 출력해서 쓰던걸 쿠키에 담아서 사용하는 걸로 변경
- close #119 
<br>
---
=> Refactor/#119 유저 아이디 쿠키에 담아서 꺼내 쓰기

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/schedule/ScheduleDAO.java, src/main/java/com/coffice/app/events/schedule/ScheduleService.java, src/main/resources/database/mappers/ScheduleMapper.xml, src/main/resources/static/js/calendar/scheduleCalendar.js
반복일정 일괄수정 가능 / 반복일정 중 단일 수정 오류 보완
- close #120 
<br>
---
=> feat: #120 일괄수정/단일수정보완

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/schedule/ScheduleDAO.java, src/main/java/com/coffice/app/events/schedule/ScheduleService.java, src/main/java/com/coffice/app/events/schedule/ScheduleVO.java, src/main/resources/database/mappers/ScheduleMapper.xml, src/main/resources/static/js/calendar/scheduleCalendar.js, src/main/webapp/WEB-INF/views/events/schedule.jsp
일정삭제 -완- (반복 일정을 단일 삭제로 다 지울 경우 반복일정status는 0으로 남지만 일정은 다 지워짐 <- 어케하지?)
- close #124 
<br>
---
=> feat: #124 일정삭제-완-

src/main/java/com/coffice/app/documents/DocumentController.java, src/main/java/com/coffice/app/documents/DocumentDAO.java, src/main/java/com/coffice/app/documents/DocumentService.java, src/main/resources/database/mappers/DocumentMapper.xml, src/main/resources/static/js/document/toReject.js, src/main/webapp/WEB-INF/views/document/form/variableForm.jsp, src/main/webapp/WEB-INF/views/document/list.jsp, src/main/webapp/WEB-INF/views/document/modal/rejectReasonModal.jsp, src/main/webapp/WEB-INF/views/templates/ocModal.jsp
=> [feat: #134] 반려 상태 업데이트 및 반려 관련 내용 조회

src/main/java/com/coffice/app/notification/NotificationController.java, src/main/java/com/coffice/app/notification/NotificationDAO.java, src/main/java/com/coffice/app/notification/NotificationService.java, src/main/java/com/coffice/app/notification/NotificationVO.java, src/main/java/com/coffice/app/posts/notice/NoticeService.java, src/main/resources/database/mappers/NotificationMapper.xml, src/main/resources/static/css/chatAlert.css, src/main/resources/static/js/notification/notification.js, src/main/webapp/WEB-INF/views/templates/top.jsp
헤더 알림 부분에 알림을 띄우는 기능
알림 더보기 클릭 시 모달창으로 추가적인 알림 볼 수 있음
- close #109 
<br>
---
=> Feat/#109 헤더에 알림 띄우기

src/main/webapp/WEB-INF/views/templates/ocModal.jsp
채팅방에서 조직도 쓸 때 로직 수정
- close #142 
<br>
---
=> Fix:142 모달 로직 수정

src/main/resources/static/js/notification/notification.js
알림 헤더에서 해당 element가 없을 때 js에서 null 예외 나는 거 오류 수정
- close #144 
<br>
---
=> Fix/#144 알림 헤더 js 오류 수정

src/main/java/com/coffice/app/notification/NotificationService.java, src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/board/BoardDAO.java, src/main/java/com/coffice/app/posts/board/BoardSerivce.java, src/main/resources/database/mappers/BoardMapper.xml, src/main/resources/static/css/chatAlert.css, src/main/resources/static/js/notification/notification.js, src/main/resources/static/js/posts/boardDetail.js, src/main/resources/static/js/posts/noticeDetail.js, src/main/webapp/WEB-INF/views/templates/footModal.jsp, src/main/webapp/WEB-INF/views/templates/top.jsp
익명게시판 댓글 알림 기능. 댓글 작성 시 원글 작성자 알림창에 알림을 뜨게 하는 기능
toast 기능으로 옆에 뜨게 함
- close #97 
<br>
---
=> Feat/#97 익명게시판 댓글 알림 기능

src/main/java/com/coffice/app/notification/NotificationService.java, src/main/java/com/coffice/app/posts/board/BoardDAO.java, src/main/java/com/coffice/app/posts/board/BoardSerivce.java, src/main/resources/database/mappers/BoardMapper.xml, src/main/resources/static/js/notification/notification.js, src/main/webapp/WEB-INF/views/board/add.jsp, src/main/webapp/WEB-INF/views/board/detail.jsp, src/main/webapp/WEB-INF/views/notice/add.jsp
익명게시판 댓글에서 답글을 달 시 댓글 작성자에게 알림이 가는 기능
- close #147 
<br>
---
=> Feat/#147 익명게시판 대댓글 알림 기능

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/EventVO.java, src/main/java/com/coffice/app/events/schedule/ScheduleService.java, src/main/java/com/coffice/app/events/vacation/VacationDAO.java, src/main/java/com/coffice/app/events/vacation/VacationService.java, src/main/java/com/coffice/app/events/vacation/VacationVO.java, src/main/resources/database/mappers/VacationMapper.xml, src/main/resources/static/js/calendar/scheduleCalendar.js, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/webapp/WEB-INF/views/events/schedule.jsp, src/main/webapp/WEB-INF/views/templates/top.jsp
휴가 신청 시 승인자를 지정, 신청 후 승인자는 승인 가능, 승인된 휴가만 캘린더 구현, 전체 휴가는 신청목록에서 조회
- close #132 
<br>
---
=> Feat/#132 휴가관리 휴가신청

src/main/java/com/coffice/app/events/holidays/HolidayDAO.java, src/main/java/com/coffice/app/events/holidays/HolidayService.java, src/main/resources/database/mappers/HolidayMapper.xml
shceduled를 이용한 holiday 5개년치 dbInsert
- close #100 
<br>
---
=> feat: #100 공휴일scheduleInsert

src/main/java/com/coffice/app/events/holidays/HolidayService.java
공휴일 api 매일 12시 delete후 insert 개발 기간 중 주석 처리 -> 테스트 기간에 주석 해제할것
- close #157
<br>
---
=> Feat/#157 공휴일schedule test

src/main/resources/static/js/calendar/homeCalendar.js, src/main/resources/static/js/calendar/scheduleCalendar.js, src/main/resources/static/js/calendar/vacationCalendar.js
ajax 경로 수정 (절대, 상대)
- close #159 
<br>
---
=> chore: #159 경로수정 완

src/main/java/com/coffice/app/posts/notice/NoticeController.java, src/main/webapp/WEB-INF/views/templates/sidebar.jsp
머지하고 난 뒤에 생긴 오류들 고침
- close #{이슈넘버}
<br>
---
=> Fix/#165 오류 수정

src/main/webapp/WEB-INF/views/templates/ocModal.jsp
=> [Fix: #169] 조직도 버튼 중복 코드 제거

src/main/java/com/coffice/app/notification/NotificationService.java
본인의 글에서 댓글을 작성했을 때 알림이 오지 않게 로직 변경
- close #172
<br>
---
=> Fix/#172 댓글 알림 로직 변경

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/vacation/VacationDAO.java, src/main/java/com/coffice/app/events/vacation/VacationService.java, src/main/resources/database/mappers/VacationMapper.xml, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/webapp/WEB-INF/views/events/schedule.jsp, src/main/webapp/WEB-INF/views/index.jsp
휴가 신청목록, 수정 -> 마이페이지 연결
일정부분 디자인 수정 (버튼, 카드)
- close #160
<br>
---
=> Feat/#160 휴가수정 마이페이지연결

src/main/webapp/WEB-INF/views/templates/sidebar.jsp
=> fix: #175 사이드바 수정

src/main/java/com/coffice/app/message/MessageController.java, src/main/java/com/coffice/app/message/MessageDAO.java, src/main/java/com/coffice/app/message/MessageService.java, src/main/java/com/coffice/app/message/MessageVO.java, src/main/resources/database/mappers/MessageMapper.xml, src/main/webapp/WEB-INF/views/message/detail.jsp, src/main/webapp/WEB-INF/views/message/receive.jsp, src/main/webapp/WEB-INF/views/message/send.jsp
이메일 상세보기 페이지. 받는 이메일과 보낸 이메일 동일한 detail 페이지 사용
- close #167 
<br>
---
=> Feat/#167 이메일 상세보기

src/main/java/com/coffice/app/message/MessageCheckVO.java, src/main/java/com/coffice/app/message/MessageController.java, src/main/java/com/coffice/app/message/MessageDAO.java, src/main/java/com/coffice/app/message/MessageService.java, src/main/java/com/coffice/app/message/MessageVO.java, src/main/resources/database/mappers/MessageMapper.xml, src/main/resources/static/js/message/messageDetail.js, src/main/webapp/WEB-INF/views/message/detail.jsp
메일 삭제 기능
- close #183 
<br>
---
=> Feat/#183 메일 삭제

src/main/java/com/coffice/app/attendance/AttendanceController.java, src/main/java/com/coffice/app/attendance/AttendanceDAO.java, src/main/java/com/coffice/app/attendance/AttendanceService.java, src/main/java/com/coffice/app/attendance/AttendanceVO.java, src/main/resources/database/mappers/AttendanceMapper.xml, src/main/resources/static/css/attendance/updateStatus.css, src/main/resources/static/js/attendance/updateStatus.js, src/main/webapp/WEB-INF/views/attendance/statusUpdate.jsp
=> feat: #179 관리자 사원근태 수정

src/main/java/com/coffice/app/message/MessageController.java, src/main/java/com/coffice/app/message/MessageDAO.java, src/main/java/com/coffice/app/message/MessageService.java, src/main/resources/database/mappers/MessageMapper.xml, src/main/webapp/WEB-INF/views/message/receive.jsp, src/main/webapp/WEB-INF/views/message/send.jsp
메일함 페이지네이션, 검색 기능
- close #{이슈넘버}
<br>
---
=> Feat/#191 메일 페이지네이션/검색

src/main/resources/static/css/user/afterLogin.css, src/main/webapp/WEB-INF/views/user/afterLogout.jsp, src/main/webapp/WEB-INF/views/user/mypage.jsp, src/main/webapp/WEB-INF/views/user/register.jsp
=> fix: #192 마이페이지 및 로그아웃 페이지 css 보완

src/main/java/com/coffice/app/documents/DocumentController.java, src/main/java/com/coffice/app/documents/DocumentService.java, src/main/java/com/coffice/app/gpt/GeminiController.java, src/main/java/com/coffice/app/ingredients/IngredientsController.java, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/ingredients/detail.jsp, src/main/webapp/WEB-INF/views/templates/sidebar.jsp
=> Refactor/#193 오류 및 css수정

src/main/java/com/coffice/app/message/MessageService.java, src/main/java/com/coffice/app/notification/NotificationService.java, src/main/resources/static/js/notification/notification.js
메일 알림 기능
- close #195 
<br>
---
=> Feat/#195 메일 알림

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/notification/NotificationDAO.java, src/main/java/com/coffice/app/notification/NotificationService.java, src/main/resources/database/mappers/NotificationMapper.xml, src/main/resources/static/js/notification/notification.js
휴가 알림
- close #203 
<br>
---
휴가 알림 넣어 놨습니다!
[휴가]       ---1
휴가 신청 ---2
1번 내용을 바꾸고 싶으실 때는 notification.js에서 createAlert 함수에 kindDiv.innerText 부분과 createToast 함수의 roomName.textContents 부분을 변경하시면 됩니다 
2번 내용을 바꾸고 싶으실 때는 notificationService에 sendVacation 부분에서 notificationVO.setNotiContents("휴가 신청"); 이 부분을 변경하시면 됩니다.
=> Feat/#203 휴가 알림

src/main/java/com/coffice/app/notification/NotificationService.java, src/main/resources/static/js/notification/notification.js
결재 알림과 참조자 알림
- close #204 
<br>
---
참조자 알림(NotificationService sendReferrenceLine())
=> ReferenceVO List 넣으시면 해당 ReferenceVO에 담겨있는 유저에게 알림이 갑니다
결재 알림(NotificationService sendApprovalLine())
1. 다음 결재 라인 알림
- DocumentVO와 다음 결재 userId, status 1을 보내주시면 됩니다
2. 모든 결재 라인 완료 후 알림
- DocumentVO와 해당 결재 문서 작성자 userId, status 값 0을 주시면 됩니다.
3. 결재 반려
- DocumentVO와 해당 결재 문서 작성자 userId, status값 2을 주시면 됩니다.
=> Feat/#204 결재 알림

src/main/java/com/coffice/app/message/MessageController.java, src/main/java/com/coffice/app/message/MessageDAO.java, src/main/java/com/coffice/app/message/MessageService.java, src/main/java/com/coffice/app/message/MessageVO.java, src/main/resources/database/mappers/BoardMapper.xml, src/main/resources/database/mappers/MessageMapper.xml, src/main/resources/database/mappers/NoticeMapper.xml, src/main/resources/static/js/message/messageReceive.js, src/main/resources/static/js/message/messageSend.js, src/main/webapp/WEB-INF/views/board/list.jsp, src/main/webapp/WEB-INF/views/message/receive.jsp, src/main/webapp/WEB-INF/views/message/send.jsp, src/main/webapp/WEB-INF/views/notice/list.jsp
메일 수신확인 기능. 보낸메일함에서 수신 확인 버튼을 누르면 비동기로 정보를 가지고 옴
- close #205 
<br>
---
=> Feat/#205 메일 수신확인

src/main/java/com/coffice/app/events/holidays/HolidayService.java, src/main/java/com/coffice/app/users/UserController.java, src/main/resources/static/js/user/history.js, src/main/webapp/WEB-INF/views/user/vacationHistory.jsp
cron수정 배포환경설정 마이페이지수정
- close #214
<br>
---
=> Refactor/#214 cron수정 배포환경설정

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/vacation/VacationService.java, src/main/java/com/coffice/app/notification/NotificationService.java, src/main/webapp/WEB-INF/views/index.jsp
휴가 신청, 승인 후 알림
- close #220
<br>
---
=> chore: #220 휴가신청승인-알림

src/main/java/com/coffice/app/chat/ChatController.java, src/main/java/com/coffice/app/message/MessageController.java, src/main/java/com/coffice/app/message/MessageService.java, src/main/java/com/coffice/app/notification/NotificationDAO.java, src/main/java/com/coffice/app/notification/NotificationService.java, src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/board/BoardSerivce.java, src/main/java/com/coffice/app/posts/board/BoardVO.java, src/main/java/com/coffice/app/posts/notice/NoticeController.java, src/main/java/com/coffice/app/posts/notice/NoticeDAO.java, src/main/java/com/coffice/app/posts/notice/NoticeService.java, src/main/java/com/coffice/app/posts/notice/NoticeVO.java, src/main/resources/database/mappers/NotificationMapper.xml, src/main/resources/static/js/notification/notification.js, src/main/webapp/WEB-INF/views/board/list.jsp, src/main/webapp/WEB-INF/views/notice/list.jsp
알림 원글 읽을 때 알림도 읽음 표시
- close #219 
<br>
---
=> Fix/#219 알림 버그 수정

src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/vacation/VacationDAO.java, src/main/java/com/coffice/app/events/vacation/VacationService.java, src/main/java/com/coffice/app/events/vacation/VacationVO.java, src/main/resources/database/mappers/VacationMapper.xml, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/webapp/WEB-INF/views/events/schedule.jsp
휴가신청 반차적용, 휴가 승인 거절 기능 추가
- close #226 
<br>
---
=> refactor: #226 반차적용, 승인거절추가

src/main/java/com/coffice/app/attendance/AttendanceDAO.java, src/main/java/com/coffice/app/attendance/AttendanceScheduler.java, src/main/java/com/coffice/app/attendance/AttendanceService.java, src/main/java/com/coffice/app/employee/EmployeeController.java, src/main/java/com/coffice/app/users/EmployeeRoleDAO.java, src/main/java/com/coffice/app/users/RoleDAO.java, src/main/java/com/coffice/app/users/UserController.java, src/main/java/com/coffice/app/users/UserService.java, src/main/resources/database/mappers/AttendanceMapper.xml, src/main/resources/database/mappers/EmployeeRoleMapper.xml, src/main/resources/database/mappers/RoleMapper.xml, src/main/resources/static/css/sidebar.css, src/main/webapp/WEB-INF/views/templates/sidebar.jsp
=> fix: #224 사이드바

src/main/java/com/coffice/app/documents/DocumentController.java, src/main/java/com/coffice/app/documents/DocumentService.java, src/main/webapp/WEB-INF/views/document/form/variableForm.jsp, src/main/webapp/WEB-INF/views/templates/sidebar.jsp
=> fix: #236 문서 관련 메뉴 및 버튼 오작동 수정

src/main/java/com/coffice/app/security/LoginFailureHandler.java, src/main/java/com/coffice/app/security/SecurityConfig.java, src/main/java/com/coffice/app/users/UserService.java, src/main/webapp/WEB-INF/views/user/login.jsp
=> fix: #244 로그인 실패 메시지 추가

src/main/java/com/coffice/app/page/Pager.java, src/main/java/com/coffice/app/users/UserVO.java, src/main/resources/static/js/chat/add.js, src/main/resources/static/js/chat/chatStomp.js, src/main/resources/static/js/message/messageAdd.js, src/main/resources/static/js/message/messageReply.js, src/main/resources/static/js/message/messageSend.js, src/main/resources/static/js/notification/notification.js, src/main/resources/static/js/posts/boardDetail.js, src/main/resources/static/js/posts/noticeAdd.js, src/main/resources/static/js/posts/noticeDetail.js, src/main/resources/static/js/posts/noticeUpdate.js, src/main/webapp/WEB-INF/views/notice/add.jsp, src/test/java/com/coffice/app/posts/board/BoardDAOTest.java, src/test/java/com/coffice/app/posts/notice/NoticeDAOTest.java
=> Fix/#247 테스트

src/main/resources/static/js/calendar/homeCalendar.js, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/resources/static/js/user/history.js, src/main/webapp/WEB-INF/views/templates/top.jsp
=> Fix/#253 테스트

src/main/java/com/coffice/app/notification/NotificationController.java, src/main/java/com/coffice/app/notification/NotificationDAO.java, src/main/java/com/coffice/app/notification/NotificationService.java, src/main/java/com/coffice/app/posts/board/BoardController.java, src/main/java/com/coffice/app/posts/board/BoardDAO.java, src/main/java/com/coffice/app/posts/board/BoardSerivce.java, src/main/java/com/coffice/app/posts/board/BoardVO.java, src/main/resources/database/mappers/BoardMapper.xml, src/main/resources/database/mappers/ChatMapper.xml, src/main/resources/database/mappers/NotificationMapper.xml, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/resources/static/js/notification/notification.js, src/main/webapp/WEB-INF/views/board/list.jsp
=> Fix/#255 공지사항 / 채팅 / 알림 수정

src/main/java/com/coffice/app/attendance/AttendanceController.java, src/main/java/com/coffice/app/attendance/AttendanceService.java, src/main/java/com/coffice/app/employee/EmployeeController.java, src/main/webapp/WEB-INF/views/employee/list.jsp
=> fix: #259 근태 퍼센티지 수정

src/main/java/com/coffice/app/notification/NotificationService.java, src/main/resources/database/mappers/ChatMapper.xml
알림 오류 수정
- close #262 
<br>
---
=> Fix/#262 알림 오류 수정

src/main/java/com/coffice/app/events/CalendarEventDTO.java, src/main/java/com/coffice/app/events/EventController.java, src/main/java/com/coffice/app/events/EventUtility.java, src/main/java/com/coffice/app/events/holidays/HolidayService.java, src/main/java/com/coffice/app/events/vacation/VacationDAO.java, src/main/java/com/coffice/app/events/vacation/VacationService.java, src/main/java/com/coffice/app/security/SecurityConfig.java, src/main/resources/database/mappers/VacationMapper.xml, src/main/resources/static/js/calendar/scheduleCalendar.js, src/main/resources/static/js/calendar/vacationCalendar.js, src/main/webapp/WEB-INF/views/events/schedule.jsp
일정 이벤트 캘린더 내장 호출 방식으로 변경
- close #264
<br>
---
=> Refactor/#264 일정 이벤트호출방식변경
